### ISSUE TITLE
Failed to fallback on IPv4 when IPv6 is not working

### ISSUE THREAD

**Issue by tutaidalal** [jacksontj/promxy#713]
I am using hostname as a target in server group. The nslookup is resolving both ipv4 and ipv6 ip. Using curl i can fetch the data from server group prometheus, however promxy is only trying to connect IPv6 and not trying to use IPv4 when the Ipv6 is not reachable. 

Can anyone suggest for any code change or any configuration that can force my application to use IPv4 only ?

**Comment by tutaidalal** [comment]
Seems like the Happy Eyeballs (RFC 6555) algorithm, which tries both IPv6 and IPv4 in parallel, is not implemented by default in Go’s net.Dial or http.Client. Is there any option to make it work to try all the IP resolved by Resolver Lookup

**Comment by jacksontj** [comment]
Promxy's connection to downstream prometheus API endpoints is all done through https://github.com/prometheus/client_golang -- which under the hood uses `net.http` which [supposedly](https://go-review.googlesource.com/c/go/+/146659) has this happy eyeballs RFC implemented.

If thats still not working; do you have an endpoint to test against?

**Comment by tutaidalal** [comment]
My endpoints are in private network and still having the issue. I can also see that when i set 'ignore_error' as false its clearly saying that its only trying to reach ipv6. For now I have modified the resolver so that any ipv6 which are not reachable will not be published and this work around worked for me. May be if i can simulate the same in some public network, will share the test endpoint.
